### ISSUE TITLE
[2pt] recipe-app: Setup project kanban board - Group Task

### ISSUE THREAD

**Issue by zieeco** [zieeco/recipe-app#16]
In this project milestone, we did the following:

- Setup the kanban board
- Assigned tasks to each member of the group

Team member 1 - @zieeco 
Team member 2 - @samiullahbahadur

This is the setup feature of our [Recipe App](https://github.com/zieeco/recipe-app)

**Comment by thecodechaser** [comment]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @zieeco, and @samiullahbahadur👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️

- [ ] Please make sure that all task cards have points that show how complex the task is, Task card #16. doesn't have the points.
![image](https://user-images.githubusercontent.com/83803414/180860064-e2683507-81bb-49ee-9afd-c69c4a7e9ffc.png)

- [ ] Time estimate distributions should be fair between team members - no single person should be doing all of the most time-consuming tasks. Task card #13 has `12pt` I think there is a typo. Please fix it.
![image](https://user-images.githubusercontent.com/83803414/180860017-1259e345-2968-46ac-925c-65b8c51fb70d.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sja-thedude** [comment]
## Project Approved 👍 

Hi @zieeco & @samiullahbahadur, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
